export const TIMELINE_CONSTANTS = {
  DAYS_TO_SHOW_NEXT_MONTH: 15,
  CELL_WIDTH: 30,
  ROW_HEIGHT: 26,
  ACTUAL_ROW_HEIGHT: 41,
  PROJECT_BAR_OPACITY: 0.6,
  INITIAL_LOAD_SIZE: 10,
  LOAD_MORE_SIZE: 10,
} as const;

